let stream, recorder, chunks=[], writeChain=Promise.resolve(), audioCtx, source, analyser, processor, anim, started=0, rid=null, stopping=false;
const $=s=>document.querySelector(s), dot=$('#dot'), label=$('#label'), timer=$('#timer'), text=$('#text'), canvas=$('#wave'), ctx=canvas.getContext('2d');
function ui(status,msg){dot.className='dot '+({recording:'live',processing:'work',done:'ok',failed:'bad'}[status]||'');label.textContent={recording:'Escuchando',processing:'Procesando',done:'Listo',failed:'Error'}[status]||status;text.className=status==='recording'?'ghost':'solid';if(msg)text.textContent=msg}
function draw(){if(!analyser)return;const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteTimeDomainData(data);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*canvas.width,y=(data[i]/255)*canvas.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle='rgba(174,180,193,.55)';ctx.lineWidth=1.5;ctx.stroke();timer.textContent=((performance.now()-started)/1000).toFixed(1)+'s';anim=requestAnimationFrame(draw)}
function floatTo16(float32){const out=new Int16Array(float32.length);for(let i=0;i<float32.length;i++){const s=Math.max(-1,Math.min(1,float32[i]));out[i]=s<0?s*0x8000:s*0x7fff}return out}
async function start(){if(stream||stopping)return;try{writeChain=Promise.resolve();stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'';recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);rid=await window.alex.recordingStarted({mime:recorder.mimeType});recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);writeChain=writeChain.then(async()=>{try{const ab=await e.data.arrayBuffer();window.alex.recordingEncodedChunk(rid,new Uint8Array(ab))}catch(_){}})}};recorder.start(500);audioCtx=new AudioContext({sampleRate:16000});source=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=256;processor=audioCtx.createScriptProcessor(4096,1,1);processor.onaudioprocess=e=>{const pcm=floatTo16(e.inputBuffer.getChannelData(0));window.alex.recordingChunk(new Uint8Array(pcm.buffer))};source.connect(analyser);source.connect(processor);processor.connect(audioCtx.destination);started=performance.now();ui('recording','Habla con naturalidad…');draw()}catch(e){ui('failed','No se pudo abrir el micrófono: '+e.message)}}
async function stop(){if(!recorder||stopping)return;stopping=true;ui('processing','Guardando audio…');cancelAnimationFrame(anim);const durationMs=performance.now()-started;await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop()});await writeChain;stream.getTracks().forEach(t=>t.stop());processor?.disconnect();source?.disconnect();await audioCtx?.close();const blob=new Blob(chunks,{type:recorder.mimeType});const ab=await blob.arrayBuffer();await window.alex.recordingFinished({id:rid,bytes:new Uint8Array(ab),mime:recorder.mimeType,durationMs});stream=null;recorder=null;processor=null;source=null;audioCtx=null;rid=null;stopping=false}
async function cancel(){if(recorder&&recorder.state!=='inactive')recorder.stop();stream?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(anim);processor?.disconnect();source?.disconnect();await audioCtx?.close();await window.alex.recordingCancelled(rid);stream=null;recorder=null;rid=null;stopping=false}
window.alex.onLiveText(d=>{if(d.text){text.textContent=d.text;text.className='ghost'}if(d.warning)label.textContent=d.warning});window.alex.onCommand(c=>c.type==='start'?start():c.type==='stop'?stop():null);window.alex.onStatus(s=>ui(s.status,s.text+(s.warning?' · '+s.warning:'')));window.addEventListener('keydown',e=>{if(e.key==='Escape')cancel()});window.alex.overlayReady();
