const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('alex', {
  state: () => ipcRenderer.invoke('state:get'),
  updateState: () => ipcRenderer.invoke('update:get'),
  checkUpdates: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  applyUpdate: () => ipcRenderer.invoke('update:apply'),
  testCredential: name => ipcRenderer.invoke('credential:test', name),
  recordingAborted: data => ipcRenderer.invoke('recording:aborted', data),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  openExternal: url => ipcRenderer.invoke('external:open', url),
  saveSettings: patch => ipcRenderer.invoke('settings:set', patch),
  saveRouting: patch => ipcRenderer.invoke('routing:set', patch),
  refreshCatalog: () => ipcRenderer.invoke('catalog:refresh'),
  saveDictionary: items => ipcRenderer.invoke('dictionary:set', items),
  saveSnippets: items => ipcRenderer.invoke('snippets:set', items),
  setSecret: (name, value) => ipcRenderer.invoke('secret:set', name, value),
  retry: id => ipcRenderer.invoke('history:retry', id),
  downloadAudio: id => ipcRenderer.invoke('history:save-audio', id),
  copyText: id => ipcRenderer.invoke('history:copy', id),
  deleteHistory: id => ipcRenderer.invoke('history:delete', id),
  diagnose: () => ipcRenderer.invoke('diagnose'),
  setupWayland: () => ipcRenderer.invoke('linux:setup-wayland'),
  registerHotkey: accelerator => ipcRenderer.invoke('hotkey:set', accelerator),
  recordingStarted: meta => ipcRenderer.invoke('recording:started', meta),
  recordingChunk: (id, chunk) => ipcRenderer.invoke('recording:pcm', { id, chunk }),
  recordingFinished: payload => ipcRenderer.invoke('recording:finished', payload),
  recordingCancelled: id => ipcRenderer.invoke('recording:cancelled', id),
  toggle: (test = false) => ipcRenderer.send('recording:toggle', { test: Boolean(test) }),
  onCommand: fn => ipcRenderer.on('overlay:command', (_e, data) => fn(data)),
  onLiveText: fn => ipcRenderer.on('overlay:live-text', (_e, data) => fn(data)),
  onStatus: fn => ipcRenderer.on('overlay:status', (_e, data) => fn(data)),
  onHint: fn => ipcRenderer.on('overlay:hint', (_e, data) => fn(data)),
  onStateChanged: fn => ipcRenderer.on('state:changed', () => fn()),
  onNotice: fn => ipcRenderer.on('notice', (_e, data) => fn(data)),
  onUpdateStatus: fn => ipcRenderer.on('update:status', (_e, data) => fn(data)),
  openSettings: () => ipcRenderer.send('window:settings')
});
